# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: daa440d9f25941cb9a2745a569e08a7d908fc6b64c8971cf8975fb120e8e4982ab04a25e3d2037ad5f4a8c6966cc758a5d611319fd8e9607f38c86f015631c12

test:
  secret_key_base: 7a997704c7d0614529ad2f0bb0859f3dd1a8dad704b53579d8f83994465a5c8ea0f0246fb2f400562d41fa5205fdaa125727fff258058d763d3fa3d8bbf9033c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
